### ISSUE TITLE
is this still working? 

### ISSUE THREAD

**Issue by highree** [Colm3na/substrate-auto-payout#5]
I get errorrs like this: 

 RPC-CORE: getMetadata(at?: BlockHash): Metadata:: createType(Metadata):: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13

API/INIT: Error: FATAL: Unable to initialize the API: createType(Metadata):: Unable to create Enum via index 14, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13

thanks for any hint.

**Comment by jaymansfield** [comment]
Upgrading @polkadot/api to 8.5.1 fixes it

**Comment by mariopino** [comment]
Hey there, didn't know this was used by anyone, updated deps as @jmansfie suggested
